name: 检查 Python 程序

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 下载代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: 检查所有 Python 文件
        run: python -m compileall .
              - name: 运行单元测试
        run: python -m unittest